name: Flet Cross-Platform Build & Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+' # v1.0.0
      - 'v[0-9]+.[0-9]+.[0-9]+-beta.[0-9]+' # v1.0.0-beta.1
  workflow_dispatch:

jobs:
  build-web-apk-linux:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: get Pixi
        run: |
          curl -fsSL https://pixi.sh/install.sh | bash
          echo "$HOME/.pixi/bin" >> $GITHUB_PATH

      - name: build web
        run: pixi run flet build web
        env:
          PYTHONUTF8: 1
          
      - name: Zip Web App
        run: |
          cd build/web
          zip -r ../flet-web-app.zip .
          
      - name: upload web
        uses: actions/upload-artifact@v4
        with:
          name: flet-web-app
          path: build/flet-web-app.zip

      - name: build apk
        run: pixi run flet build apk -v
        env:
          PYTHONUTF8: 1
          
      - name: upload APK
        uses: actions/upload-artifact@v4
        with:
          name: flet-apk-app
          path: build/apk

  build-macos-ios:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        
      - name: get pixi
        run: |
          curl -fsSL https://pixi.sh/install.sh | bash
          echo "$HOME/.pixi/bin" >> $GITHUB_PATH
          
      - name: build macos
        run: pixi run flet build macos
        env:
          PYTHONUTF8: 1
          
      - name: upload macos
        uses: actions/upload-artifact@v4
        with:
          name: flet-macos-app
          path: build/macos

      - name: build ipa
        run: pixi run flet build ipa
        env:
          PYTHONUTF8: 1
          
      - name: Export IPA from .xcarchive
        run: |
          cd build/ipa
          zip -r ../flet-ios-app.zip .
          # TODO: need apple developer id for plist
          # xcodebuild -exportArchive \
          #   -archivePath Runner.xcarchive \
          #   -exportOptionsPlist ExportOptions.plist \
          #   -exportPath . \
          #   -allowProvisioningUpdates
          
          # ls -la
          # if [ -f "Runner.ipa" ]; then
          #   echo "IPA file successfully generated: Runner.ipa"
          # else
          #   echo "Error: IPA file not found!"
          #   exit 1
          # fi
        
      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: artifacts/flet-ios-app/Runner.ipa

  build-windows:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: get pixi
        run: |
          Invoke-WebRequest -Uri "https://github.com/prefix-dev/pixi/releases/latest/download/pixi-x86_64-pc-windows-msvc.exe" -OutFile "pixi.exe"
          New-Item -ItemType Directory -Force -Path "C:\pixi-bin" | Out-Null
          Move-Item pixi.exe C:\pixi-bin\pixi.exe -Force
          echo "C:\pixi-bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        shell: pwsh
    
      - name: build win
        run: pixi run flet build windows
        env:
          PYTHONUTF8: 1
          
      - name: upload win
        uses: actions/upload-artifact@v4
        with:
          name: flet-windows-app
          path: build/windows

  release:
    runs-on: ubuntu-latest
    needs: [build-web-apk-linux, build-macos-ios, build-windows]
    permissions:
      contents: write
    steps:
      - name: download all
        uses: actions/download-artifact@v4
        with:
          path: artifacts 

      - name: show file tree
        run: find . -maxdepth 2 -type d -ls

      - name: publish release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            自动构建的 Flet 应用产物。
            - Web 应用
            - Android APK
            - macOS 应用
            - iOS 应用 (IPA)
            - Windows 应用
          prerelease: ${{ contains(github.ref_name, '-beta') }}
          files: |
            # Android APK
            artifacts/flet-apk-app/app-release.apk
            artifacts/flet-apk-app/app-release.apk.sha1
            
            # iOS 应用
            artifacts/flet-ios-app.zip
            
            # macOS 应用 (适配不同打包格式)
            artifacts/flet-macos-app/*.app
            artifacts/flet-macos-app/*.dmg
            artifacts/flet-macos-app/*.zip
            
            # Windows 应用
            artifacts/flet-windows-app/*.exe
            artifacts/flet-windows-app/*.msi
            
            # Web 应用
            artifacts/flet-web-app/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
