name: Build Flet App for All Platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_linux:
    runs-on: ubuntu-latest
    name: Build Linux/APK/Web
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install 'flet[all]'
          # 安装其他必要的依赖
          # pip install -r requirements.txt
          
      - name: Build APK
        run: flet build apk -v
        
      - name: Build Web
        run: flet build web -v
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: linux-builds
          path: |
            build/
            dist/

  build_macos:
    needs: build_linux
    runs-on: macos-latest
    name: Build iOS/macOS
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install 'flet[all]'
          
      - name: Build iOS
        run: flet build ios -v
        
      - name: Build macOS
        run: flet build macos -v
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: macos-builds
          path: |
            build/
            dist/

  build_windows:
    needs: build_linux
    runs-on: windows-latest
    name: Build Windows
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install 'flet[all]'
          
      - name: Build Windows
        run: flet build windows -v
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-builds
          path: |
            build/
            dist/
